#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

if [[ $# -gt 0 && "$1" != --* ]]; then
  RUN_NAME="$1"
  shift
else
  RUN_NAME="fast-$(date +%Y%m%d-%H%M%S)"
fi

if [[ -n "${PYTHON_BIN:-}" ]]; then
  PYTHON_CMD="$PYTHON_BIN"
elif [[ -x ".venv/bin/python" ]]; then
  PYTHON_CMD=".venv/bin/python"
else
  PYTHON_CMD="python3"
fi

DEEP_MODELS="${DEEP_MODELS:-dense,gru_artist,lstm}"
CLASSICAL_MODELS="${CLASSICAL_MODELS:-logreg,extra_trees,mlp}"
EPOCHS="${EPOCHS:-4}"
OPTUNA_TRIALS="${OPTUNA_TRIALS:-8}"
BACKTEST_FOLDS="${BACKTEST_FOLDS:-2}"

export SPOTIFY_TF_DATA_CACHE="${SPOTIFY_TF_DATA_CACHE:-off}"
export SPOTIFY_CLASSICAL_MODEL_WORKERS="${SPOTIFY_CLASSICAL_MODEL_WORKERS:-1}"
export SPOTIFY_BACKTEST_WORKERS="${SPOTIFY_BACKTEST_WORKERS:-1}"
export SPOTIFY_OPTUNA_JOBS="${SPOTIFY_OPTUNA_JOBS:-1}"
export SPOTIFY_ROBUSTNESS_GUARDRAIL_SEGMENT="${SPOTIFY_ROBUSTNESS_GUARDRAIL_SEGMENT:-repeat_from_prev}"
export SPOTIFY_ROBUSTNESS_GUARDRAIL_BUCKET="${SPOTIFY_ROBUSTNESS_GUARDRAIL_BUCKET:-new}"
export SPOTIFY_STRESS_BENCHMARK_SCENARIO="${SPOTIFY_STRESS_BENCHMARK_SCENARIO:-evening_drift}"
export SPOTIFY_STRESS_BENCHMARK_POLICY="${SPOTIFY_STRESS_BENCHMARK_POLICY:-safe_global}"
export SPOTIFY_STRESS_BENCHMARK_REFERENCE_POLICY="${SPOTIFY_STRESS_BENCHMARK_REFERENCE_POLICY:-baseline_exploit}"
export SPOTIFY_CONFORMAL_TARGET_SELECTIVE_RISK="${SPOTIFY_CONFORMAL_TARGET_SELECTIVE_RISK:-0.45}"
export SPOTIFY_CONFORMAL_MIN_ACCEPTED_RATE="${SPOTIFY_CONFORMAL_MIN_ACCEPTED_RATE:-0.20}"
export SPOTIFY_CONFORMAL_MIN_RISK_DROP="${SPOTIFY_CONFORMAL_MIN_RISK_DROP:-0.02}"
export SPOTIFY_CHAMPION_GATE_METRIC="${SPOTIFY_CHAMPION_GATE_METRIC:-backtest_top1}"
export SPOTIFY_CHAMPION_GATE_MATCH_PROFILE="${SPOTIFY_CHAMPION_GATE_MATCH_PROFILE:-1}"
export SPOTIFY_CHAMPION_GATE_MAX_REGRESSION="${SPOTIFY_CHAMPION_GATE_MAX_REGRESSION:-0.01}"
export SPOTIFY_CHAMPION_GATE_MAX_SELECTIVE_RISK="${SPOTIFY_CHAMPION_GATE_MAX_SELECTIVE_RISK:-0.55}"
export SPOTIFY_CHAMPION_GATE_MAX_ABSTENTION_RATE="${SPOTIFY_CHAMPION_GATE_MAX_ABSTENTION_RATE:-0.35}"
export SPOTIFY_DISABLE_MONITOR="${SPOTIFY_DISABLE_MONITOR:-1}"

exec "$PYTHON_CMD" -m spotify \
  --profile fast \
  --run-name "$RUN_NAME" \
  --epochs "$EPOCHS" \
  --models "$DEEP_MODELS" \
  --classical-models "$CLASSICAL_MODELS" \
  --optuna \
  --optuna-trials "$OPTUNA_TRIALS" \
  --optuna-models "$CLASSICAL_MODELS" \
  --temporal-backtest \
  --backtest-folds "$BACKTEST_FOLDS" \
  --backtest-models "$CLASSICAL_MODELS" \
  --mlflow \
  --no-shap \
  "$@"
